In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
name =['sepal-length','sepal-width','petal-length','petal-width','class']
ds = pd.read_csv(url,names=name)

In [3]:
 ds

sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
x= ds.iloc[:,:-1].values
y=ds.iloc[:,4].values

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)

In [6]:
from sklearn.preprocessing import StandardScaler
sclr = StandardScaler()
sclr.fit(x_train)
x_train = sclr.transform(x_train)
x_test = sclr.transform(x_test)

In [7]:
from sklearn.neighbors import KNeighborsClassifier
clsfr = KNeighborsClassifier(n_neighbors=5)
clsfr.fit(x_train,y_train)

KNeighborsClassifier()

In [8]:
y_pred = clsfr.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.92      1.00      0.96        12
 Iris-virginica       1.00      0.91      0.95        11

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

[[ 7  0  0]
 [ 0 12  0]
 [ 0  1 10]]
