In [3]:
import numpy as np
list = [1,2,3,4,5]
sam_arr=np.array(list)
print("list",list)
print("Numpy Array:",sam_arr)

list [1, 2, 3, 4, 5]
Numpy Array: [1 2 3 4 5]


In [4]:
print(type(list))
print(type(sam_arr))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
l1=[1,2,3,4]
l2=[4,5,6,7]
l3=[7,8,9,0]
sam_arr= np.array([l1,l2,l3])
print("numpy multi dimantion array\n",sam_arr)

numpy multi dimantion array
 [[1 2 3 4]
 [4 5 6 7]
 [7 8 9 0]]


In [8]:
print("shap of array",sam_arr.shape)

shap of array (3, 4)


In [10]:
sam1=np.array([[0,4,8]])
sam2=np.array([[0.24,0.25,12.35]])
print("data type of array1",sam1.dtype)
print("data type of array2",sam2.dtype)

data type of array1 int64
data type of array2 float64


In [16]:
iterable =(a*a for a in range(8))
arr = np.fromiter(iterable,int)
print(arr)

[ 0  1  4  9 16 25 36 49]


In [17]:
var = "RajRatan "
arr=np.fromiter(var,dtype="U2")
print(arr)

['R' 'a' 'j' 'R' 'a' 't' 'a' 'n' ' ']


In [22]:
np.arange(1,99,2,dtype=np.float64)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97.])

In [29]:
np.arange(1,9900,3,dtype=np.int32)

array([   1,    4,    7, ..., 9892, 9895, 9898], dtype=int32)

In [48]:
np.linspace(3,100,4)
#starting end slice 

array([  3.        ,  35.33333333,  67.66666667, 100.        ])

In [49]:
np.empty([4, 3],
         dtype=np.int32,
         order='f')

array([[1208063184,          0,          0],
       [     32549,          0,          0],
       [         0,          0,          0],
       [         0,          0,          0]], dtype=int32)

In [50]:
np.ones([4,3],
       dtype=np.int32,
       order ='f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [57]:
np.zeros([5,3],
       dtype=np.float64,
       order ='f')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])